### ISSUE TITLE
running ConFix on an example?

### ISSUE THREAD

**Issue by monperrus** [thwak/ConFix#1]
Hi,
I'm trying to run ConFix on an example. I can successfully compile and start the main class.

```
git clone https://github.com/thwak/ConFix/
cd ConFix
mvn install
mvn exec:java -Dexec.mainClass=com.github.thwak.confix.main.ConFix
```

This crashes as follows. What setup would you recommend to run ConFix on an example?

```
java.io.FileNotFoundException: confix.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.github.thwak.confix.main.ConFix.loadProperties(ConFix.java:480)
	at com.github.thwak.confix.main.ConFix.main(ConFix.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
java.io.FileNotFoundException: tests.trigger (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.github.thwak.confix.util.IOUtils.readFile(IOUtils.java:27)
	at com.github.thwak.confix.util.IOUtils.readFile(IOUtils.java:48)
	at com.github.thwak.confix.main.ConFix.loadTests(ConFix.java:287)
	at com.github.thwak.confix.main.ConFix.main(ConFix.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
java.io.FileNotFoundException: tests.relevant (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.github.thwak.confix.util.IOUtils.readFile(IOUtils.java:27)
	at com.github.thwak.confix.util.IOUtils.readFile(IOUtils.java:48)
	at com.github.thwak.confix.main.ConFix.loadTests(ConFix.java:288)
	at com.github.thwak.confix.main.ConFix.main(ConFix.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
java.io.FileNotFoundException: tests.all (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.github.thwak.confix.util.IOUtils.readFile(IOUtils.java:27)
	at com.github.thwak.confix.util.IOUtils.readFile(IOUtils.java:48)
	at com.github.thwak.confix.main.ConFix.loadTests(ConFix.java:289)
	at com.github.thwak.confix.main.ConFix.main(ConFix.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
java.io.FileNotFoundException: coverage-info.obj (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.github.thwak.confix.util.IOUtils.readObject(IOUtils.java:129)
	at com.github.thwak.confix.util.IOUtils.readObject(IOUtils.java:121)
	at com.github.thwak.confix.main.ConFix.loadCoverage(ConFix.java:522)
	at com.github.thwak.confix.main.ConFix.main(ConFix.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by thwak** [comment]
It seems that some files are not in the working directory.

Check this for what is each file. - https://github.com/thwak/ConFix/blob/master/README.md <https://github.com/thwak/ConFix/blob/master/README.md>

For sample execution, I recommend you to try https://github.com/thwak/confix2019result/tree/master/replication <https://github.com/thwak/confix2019result/tree/master/replication>.


Regards,
Jindae

**Comment by monperrus** [comment]
Thanks a lot for the information.

**Comment by CloudLeeus** [comment]
Hi,
I'm trying to run ConFix on an example.However, I encountered a problem.
This crashes as follows. What setup would you recommend to run ConFix on an example?


**No class/coverage information.
java.io.FileNotFoundException: **coverage-info.obj** 
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.github.thwak.confix.util.IOUtils.readObject(IOUtils.java:129)
	at com.github.thwak.confix.util.IOUtils.readObject(IOUtils.java:121)
	at com.github.thwak.confix.main.ConFix.loadCoverage(ConFix.java:522)
	at com.github.thwak.confix.main.ConFix.main(ConFix.java:78)**

Looking forward to your reply, thank you!

**Comment by Jindae** [comment]
You need to create `coverage-info.obj` for your example.    
It is an instance of serializable `CoverageManager` contains coverage information, hence create an instance and store it to the file, and put it in the directory you're running ConFix.   
You can also try an example from a replication package https://github.com/thwak/confix2019result/tree/master/replication too.

**Comment by CloudLeeus** [comment]
> You need to create `coverage-info.obj` for your example. It is an instance of serializable `CoverageManager` contains coverage information, hence create an instance and store it to the file, and put it in the directory you're running ConFix. You can also try an example from a replication package https://github.com/thwak/confix2019result/tree/master/replication too.

Thanks a lot for the information. In addition, I want to ask a question: is the change collection collected before the tool runs or when the tool runs? Thank you!

**Comment by thwak** [comment]
It is designed to run with pre-collected changes. Once you collect changes, you can use them repeatedly.

**Comment by CloudLeeus** [comment]
![image](https://user-images.githubusercontent.com/77276373/167758027-18ac803c-d159-43ee-95d8-8911577137e9.png)

**import script.model.EditOp;
import tree.TreeNode;**

First of all, thank you very much for your last reply. These two packages cannot be imported normally. What are the good solutions

**Comment by CloudLeeus** [comment]
Hi!
   I have successfully run the example **chart10b** you gave.
   However，I'm trying to run ConFix on lang1b.
   Run：
          defects4j checkout -p Lang -v 1b -w lang1b
          cd lang1b  
          defects4j compile
   The following results are produced:
![image](https://user-images.githubusercontent.com/77276373/182786326-068ef255-1d55-4a7c-b74e-5e74e02e12eb.png)
   Now,I have created confix.properties and tests.*.In this step, I have two questions to ask you.
   (1)In confix.properties:
        ①cp.compile=xxxxxxx
        in  the lang1b  don't have **build**  and **servlet.jar**
        ②cp.test=xxxxxxx
        in  the lang1b  don't have **servlet.jar** and **build-test**
  This problem has bothered me for a long time. I really hope to get your help. Thank you！

**Comment by CloudLeeus** [comment]
Now this problem has been solved. I didn't understand the configuration file before and now I understand it.
